### ISSUE TITLE
cannot import name 'DomainClient'

### ISSUE THREAD

**Issue by winstonpgao** [andycasey/get-rich-or-die-trying#4]
Hi,

I am not sure why I cann't import the DomainClient.
Plz help, thanks!

![image](https://user-images.githubusercontent.com/26820872/106589691-66467b80-65a0-11eb-99ef-ea9e8b6334b5.png)

**Comment by andycasey** [comment]
Seems like a path issue that I can’t fix without more information. Either way, probably stale by now.
